CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monitors (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    label VARCHAR(100) NOT NULL,
    url TEXT NOT NULL,
    interval_mins INT NOT NULL DEFAULT 5,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS status_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    monitor_id BIGINT UNSIGNED NOT NULL,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response_code INT,
    response_time_ms INT,
    is_success BOOLEAN NOT NULL,
    error_msg TEXT,
    FOREIGN KEY (monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alerts_sent (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    monitor_id BIGINT UNSIGNED NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alert_type ENUM('email', 'webhook') NOT NULL,
    method VARCHAR(100) NOT NULL,
    FOREIGN KEY (monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
);

ALTER TABLE users
    ADD COLUMN plan ENUM('free', 'pro', 'enterprise') NOT NULL DEFAULT 'free';
